spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hardware_import_version_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useOldAliasMetadataBehavior=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
          hibernate:
            dialect : org.hibernate.dialect.MySQL5Dialect
